enum types {
  DATA_LOAD = 'DATA_LOAD',
  DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS',
  DATA_LOAD_FAIL = 'DATA_LOAD_FAIL',
  DATA_LOAD_MORE = 'DATA_LOAD_MORE',
  DATA_LOAD_MORE_SUCCESS = 'DATA_LOAD_MORE_SUCCESS',
  DATA_LOAD_MORE_FAIL = 'DATA_LOAD_MORE_FAIL',
  DATA_DELETE = 'DATA_DELETE',
  DATA_DELETE_SUCCESS = 'DATA_DELETE_SUCCESS',
  DATA_DELETE_FAIL = 'DATA_DELETE_FAIL',
  SET_META = 'SET_META'
}

export default types;
